version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12 #

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - v1-pkg-{{ checksum "go.sum" }}

      - run: go get golang.org/x/tools/cmd/goimports
      - run: go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: go mod download

      - run: make precommit

      - save_cache:
          key: v1-pkg-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"

      - store_artifacts:
          path: /tmp/test-results
          destination: opentelemetry-go-test-output

      - store_test_results:
          path: /tmp/test-results
