name: Benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch: 

env:
  DEFAULT_GO_VERSION: "~1.22.5"
jobs:
  benchmark:
    name: Benchmarks
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - name: Run benchmarks
        run: make benchmark | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./benchmarks
          # Use the current commit SHA as the cache key.
          # This key won't exist on the first run, so the cache match falls back to restore-keys.
          # Though, it won't be matched, the cache created will use this key as the cache key.
          # So the next commit will be able to restore this cache (from the restore-keys).
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
          key: ${{ runner.os }}-benchmark-${{ github.sha }}
          # `github.event.before` means the commit before the push (i.e. the previous commit).
          # So we can fetch the exact benchmark data from the previous commit.
          restore-keys: ${{ runner.os }}-benchmark-${{ github.event.before }}
      - name: Store benchmarks result
        uses: benchmark-action/github-action-benchmark@v1.20.3
        with:
          name: Benchmarks
          tool: 'go'
          output-file-path: output.txt
          external-data-json-path: ./benchmarks/data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: benchmarks
          fail-on-alert: true
          alert-threshold: "400%"
          # Add benchmark summary to GitHub workflow run report
          summary-always: true
