name: full-docs-check
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  # Everyday at 9:00 AM.
  - cron: "0 9 * * *"
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run linter
      uses: docker://avtodev/markdown-lint:v1
      with:
        config: .markdownlint.yaml
        args: '**/*.md'

  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # This doesn't use gaurav-nelson/github-action-markdown-link-check
    # intentionally. As of v1.0.13 the base image was not pinned to a LTS
    # version of node and updates upstream to the base image caused CI
    # failures. This boils down the entrypoint script from that repository
    # and calls markdown-link-check directly instead.
    - run: npm install -g markdown-link-check
    - run: find . -type f -name '*.md' | xargs markdown-link-check --verbose --config .markdown-link.json
