name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  verify_readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run readme.sh
        run: ./verify_readmes.sh
