name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  readme_presence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: Run readme.sh
        run: ./.github/workflows/scripts/readme.sh
